### ISSUE TITLE
Make code modular

### ISSUE THREAD

**Issue by bhargavkaranam** [MUSoC/DigitalOcean-Messenger-Bot#1]
@Diuda 
Put all variables that can change in future or are bound to be reused - like access tokens, database credentials, common modules in config.js file. Use exports or module.exports to make it available across files.

**Comment by Diuda** [comment]
added the config file with module.exports and imported it in index.js

**Comment by bhargavkaranam** [comment]
I don't see a config.js
Also, please separate messenger function and put them in a file say messenger.js
Index.js should only have routes and they should call functions in other files. Makes it more readable. Also no hardcoding. That's why one central configuration file.  @Diuda
